### ISSUE TITLE
Error on running hawkinit bin

### ISSUE THREAD

**Issue by xeviknal** [hawkular/hawkinit#41]
Hello everyboy,

I am new working with whole environment of Hawkular. I will be part of ManageIQ-middleware team.
Right now, I am working on a pretty old Ubuntu version 14.04 LTS  (new laptop will be provided soon).

After running the `hawkinit` bin I got the following error:

```
TypeError: version.split is not a function occured when parsing this output: 17.06.2-ce, after calling docker --version | cut -f3 -d' '
```

Could you please give any hint on that? 

I don't have any expertise on docker yet.

Thanks in advanced

Xevi
